services:
  tmodloader:
    image: 'jacobsmile/tmodloader1.4:latest'
    container_name: 'tmodloader'
    ports:
      - "7777:7777"
    expose:
      - "7777"
    environment:
      # Download the Calamity mod and CalamityMusic mod.
      - "TMOD_AUTODOWNLOAD=2824688266,2908170107,2824688072,2563309347"
      # Enable the Calamity mod and CalamityMusic mod.
      - "TMOD_ENABLEDMODS=2824688266,2908170107,2824688072,2563309347"
      # Shutdown Message and Autosave Interval (In Minutes)
      - "TMOD_SHUTDOWN_MESSAGE=bye bye"
      - "TMOD_AUTOSAVE_INTERVAL=15"
      # Server Settings
      - "TMOD_MOTD=welcome xiaojie expeditioners!"
      - TMOD_PASS=${TMOD_PASS}
      - "TMOD_MAXPLAYERS=16"
      # The following world settings are only used when generating a new world.
      - "TMOD_WORLDNAME=xiaojieverse"
      - "TMOD_WORLDSIZE=2"
      - "TMOD_WORLDSEED=xiaojie"
      - "TMOD_DIFFICULTY=1"
      # (Deprecated) If TMOD_USECONFIGFILE is set to "Yes", it is expected to have a serverconfig.txt mapped. The Server Settings above will be ignored.
      - "TMOD_USECONFIGFILE=No"
      - "UPDATE_NOTICE=false"

    volumes:
    ##### By default, the below setting will create a data directory on your host where this compose file lives.
      - "./data:/data"
      # Uncomment the below line if you plan to use a mapped config file. 
      # - "/path/to/config/config.txt:/root/terraria-server/serverconfig.txt"