api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: cloudflare

providers:
  docker:
    exposedByDefault: false

serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  cloudflare:
    acme:
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare