bindaddress = "[::]:8443"

db_path = "/data/kanidm.db"

tls_chain = "/data/chain.pem"
tls_key = "/data/key.pem"

domain = "sso.cow.pet"
origin = "https://sso.cow.pet"

# [online_backup]
# path = "/data/kanidm/backups/"
# schedule = "00 22 * * *"
