services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      PAPER_CHANNEL: "experimental"
      MOTD: "\u00a7c\u00a7l@ mc.cow.pet @\u00a7r\n\u00a73MEET MILFS\u00a7r | \u00a76PET COWS\u00a7r | \u00a7dPUNCH MINORS"
      ICON: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Spot_the_cow.png"
      MODRINTH_PROJECTS: >
        bluemap,
        imageframe,
        sleeper,
        chunky,
        interactionvisualizer,
        invsee++,
        axgraves,
        tgbridge:Z4RercuF,
      MEMORY: 4G
    volumes:
      - /mnt/ssd/mc:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mc.entrypoints=web"
      - "traefik.http.routers.mc.rule=Host(`mc.cow.pet`) && PathPrefix(`/map/`)"
      - "traefik.http.routers.mc.middlewares=strip-map"
      - "traefik.http.middlewares.strip-map.stripPrefix.prefixes=/map"
      - "traefik.http.routers.mc-secure.entrypoints=websecure"
      - "traefik.http.routers.mc-secure.rule=Host(`mc.cow.pet`) && PathPrefix(`/map/`)"
      - "traefik.http.routers.mc-secure.middlewares=strip-map"
      - "traefik.http.services.mc.loadbalancer.server.port=8100"
    networks:
      - traefik
    restart: always
  mc-backup:
    image: itzg/mc-backup
    environment:
      BACKUP_ON_STARTUP: true
      PRUNE_BACKUPS_DAYS: 3
      BACKUP_INTERVAL: "12h"
      RCON_HOST: mc
    volumes:
      - /mnt/ssd/mc:/data:ro
      - /mnt/ssd/mc-backups:/backups
    restart: always


networks:
  traefik:
    external: true