services:
  mc-nginx:
    image: nginx
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./www:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.routers.nginx.rule=Host(`mc.cow.pet`)"
      - "traefik.http.routers.nginx-secure.entrypoints=websecure"
      - "traefik.http.routers.nginx-secure.rule=Host(`mc.cow.pet`)"
    networks:
      - traefik
    restart: always

networks:
  traefik:
    external: true