services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ../:/opt/stacks
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockge.entrypoints=web"
      - "traefik.http.routers.dockge.rule=Host(`containers.cow.pet`)"
      - "traefik.http.routers.dockge-secure.entrypoints=websecure"
      - "traefik.http.routers.dockge-secure.rule=Host(`containers.cow.pet`)"
      - "traefik.http.services.dockge.loadbalancer.server.port=5001"
    networks:
      - traefik

networks:
  traefik:
    external: true
