services:
  vanilla-backup:
    image: itzg/mc-backup
    environment:
      BACKUP_ON_STARTUP: false
      PRUNE_BACKUPS_DAYS: 3
      BACKUP_INTERVAL: "12h"
      RCON_HOST: mc
    volumes:
      - /mnt/ssd/mc:/data:ro
      - /mnt/hdd/mc-backups:/backups
    restart: always

