services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    restart: always
    user: "1000:1000"
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - IP6_PROVIDER=none
      - CLOUDFLARE_API_TOKEN=${CF_API_KEY}
      - DOMAINS=cow.pet, mc.cow.pet, sso.cow.pet
      - PROXIED=false
      - QUIET=true