services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      PAPER_CHANNEL: "experimental"
      MOTD: "\u00a7c\u00a7l@ mc.cow.pet @\u00a7r\n\u00a73MEET MILFS\u00a7r | \u00a76PET COWS\u00a7r | \u00a7dPUNCH MINORS"
      ICON: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Spot_the_cow.png"
      MODRINTH_PROJECTS: >
        bluemap,
        imageframe,
        sleeper,
        chunky,
        interactionvisualizer,
        invsee++,
        axgraves,
        interactivechat,
        tgbridge,
      MEMORY: 4G
    volumes:
      - /mnt/ssd/mc:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mc.entrypoints=web"
      - "traefik.http.routers.mc.rule=Host(`mc.cow.pet`) && PathPrefix(`/map/`)"
      - "traefik.http.routers.mc.middlewares=strip-map"
      - "traefik.http.middlewares.strip-map.stripPrefix.prefixes=/map"
      - "traefik.http.routers.mc-secure.entrypoints=websecure"
      - "traefik.http.routers.mc-secure.rule=Host(`mc.cow.pet`) && PathPrefix(`/map/`)"
      - "traefik.http.routers.mc-secure.middlewares=strip-map"
      - "traefik.http.routers.mc-secure.tls=true"
      - "traefik.http.routers.mc-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.mc.loadbalancer.server.port=8100"

  
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_ON_STARTUP: false
      PRUNE_BACKUPS_DAYS: 7
      BACKUP_INTERVAL: "4h"
      RCON_HOST: mc
      PRE_BACKUP_SCRIPT: |
        echo "Before backup!"
        echo "Also before backup from $$RCON_HOST to $$DEST_DIR"
      POST_BACKUP_SCRIPT_FILE: /post-backup.sh
    volumes:
      - /mnt/ssd/mc:/data:ro
      - /mnt/hdd/mc-backups:/backups
      - ./post-backup.sh:/post-backup.sh:ro

  nginx:
    image: nginx
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./www:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.routers.nginx.rule=Host(`mc.cow.pet`)"
      - "traefik.http.routers.nginx-secure.entrypoints=websecure"
      - "traefik.http.routers.nginx-secure.rule=Host(`mc.cow.pet`)"
      - "traefik.http.routers.nginx-secure.tls=true"
      - "traefik.http.routers.nginx-secure.tls.certresolver=cloudflare"